# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 14:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('askquestions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='nejor_respuesta',
            new_name='mejor_respuesta',
        ),
    ]
