# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PackageCinnamon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50, verbose_name='nombre paquete')),
            ],
        ),
        migrations.CreateModel(
            name='PackageCinnamonEdu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50, verbose_name='nombre paquete')),
            ],
        ),
        migrations.CreateModel(
            name='PackageGeneric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50, verbose_name='nombre paquete')),
            ],
        ),
        migrations.CreateModel(
            name='PackageGenericEdu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50, verbose_name='nombre paquete')),
            ],
        ),
        migrations.CreateModel(
            name='PackageMate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50, verbose_name='nombre paquete')),
            ],
        ),
        migrations.CreateModel(
            name='PackageMateEdu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50, verbose_name='nombre paquete')),
            ],
        ),
        migrations.CreateModel(
            name='Repositorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50, verbose_name='nombre proyecto')),
                ('Url', models.CharField(max_length=100, verbose_name='url repositorio del proyecto')),
            ],
        ),
    ]
